myapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views
urlpatterns = [
    url(r'^$',  views.index, name='index'),
    url(r'^myquiz/', include('myquiz.urls')),
    url(r'^admin/', admin.site.urls),
]

myquiz/urls.py
from django.conf.urls import url

from . import views
app_name = 'myquiz'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^detail/$', views.detail, name='detail'),
    url(r'^results/$', views.results, name='results'),
    url(r'^answer/$', views.answer, name='answer'),
]

myquiz/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    select_choice = models.BooleanField(default=False)

    def __str__(self):
        return self.choice_text


class User(models.Model):
    User_text = models.CharField(max_length=200)
    point = models.IntegerField(default=0)

    def __str__(self):
        return self.User_text

myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
def index(request):
    return render(request, 'main/main.html')
    #return HttpResponse("Hello, world. You're at the polls index.")

myquiz/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from .models import Question, Choice


def index(request):
    return render(request, 'myquiz/index.html', {})


def detail(request):
    question_list = Question.objects.all()
    return render(request, 'myquiz/detail.html', {
        'question_list': question_list
    })


def results(request):
    all_question = Question.objects.all()
    total_point = 0
    user_ans = []
    for question in all_question:
        is_correct = request.POST.get(str(question.id), 'False')
        user_ans.append({
            'question': question.question_text,
            'given_answer': is_correct
        })
        if is_correct == 'True':
            total_point += 1

    context = {'point': total_point, 'user_ans': user_ans}
    return render(request, 'myquiz/results.html', context)


def answer(request):
    question_list = Question.objects.all()
    return render(request, 'myquiz/answer.html', {'question_list': question_list})

myquiz/templates/main/main.html
<html>
<head>
<style>
body {
    background-color: lightpink;
}

h1 {
    color: black;
}
Try it Yourself »

</style>
</head>
<body>

<center><h1>Wellcome to my app</h1></center>
<p>App list</p>
 <a href="{% url 'myquiz:index' %}">Quiz cartoon</a></br>
</body>
</html>

myquiz/templates/myquiz/answer.html
{% load static %}
<html>
<link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}" />
<body>
<h1>Answer Question</h1>


{% for question in question_list %}
    {{ forloop.counter }}.
    {{ question.question_text }} :: 
{% for choice in question.choice_set.all %}
    {% if choice.select_choice %}
    {{ choice.choice_text }} <br>
    {% endif %}
{% endfor %}
{% endfor %}

<br><a href="{% url 'myquiz:index' %}">back to menu</a>
<br><a href="{% url 'index' %}">back main</a></br>
</html>
    

myquiz/templates/myquiz/detail.html
{% load static %}
<html>
<link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}" />
<body>
<h1>Quiz Cartoon</h1>
<form action="{% url 'myquiz:results' %}" method="post">
{% csrf_token %}
{% for question in question_list %}
    {{ forloop.counter }}.
    {{ question.question_text }}<br>
  
{% for choice in question.choice_set.all %}
    <input type="radio" name="{{ question.id }}" id="choice{{ forloop.counter }}" value="{{choice.select_choice}}"/>
    {{ choice.choice_text }}.<br>
    {% endfor %}
<br>
{% endfor %}

<input type="submit" class="button" value="submit" />
</form>

</body>
</html>

myquiz/templates/myquiz/index.html
{% load static %}
<html>
<link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<body>
    <center><h1>Wellcome to Cartoon quiz</h1></center>
    <center><i class="fa fa-car" style="font-size:48px;color:red;"></i></center>
    <center><a href="{% url 'myquiz:detail' %}">Start quiz</a></center>
    <center><a href="{% url 'index' %}">back main</a></br></center>
</body>
</html>
    

myquiz/templates/myquiz/results.html
{% load static %}
<html>
<link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}" />
<body>
<h1>You Score</h1>

{{point}}  point.<br><br>
{% for answer in user_ans %}
     {{ forloop.counter }}.{{ answer.question }}. Result: {{ answer.given_answer }}<br>
{% endfor %}

<br><a href="{% url 'myquiz:answer' %}">Answer</a></br>
<a href="{% url 'myquiz:index' %}">back to menu</a>
<br><a href="{% url 'index' %}">back main</a></br>
</body>
</html>
    

myquiz/templates/myquiz/show_score.html
<h1>Answer Question</h1>


{% for question in question_list %}
    {{ forloop.counter }}.
    {{ question.question_text }} :: 
{% for choice in question.choice_set.all %}
    {% if choice.select_choice %}
    {{ choice.choice_text }} <br>
    {% endif %}
{% endfor %}
{% endfor %}

<br><a href="{% url 'myquiz:index' %}">back to menu</a></br>